// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "Logged a more contextual error in this case.", Scope = "member", Target = "~M:WRA.Umbraco.Composers.ContentPublishedCacheNotificationHandler.Handle(Umbraco.Cms.Core.Notifications.ContentPublishedNotification)")]
[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "Logged a more contextual error in this case.", Scope = "member", Target = "~M:WRA.Umbraco.Composers.MemberSavedCacheNotificationHandler.Handle(Umbraco.Cms.Core.Notifications.MemberSavedNotification)")]
[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "Logged a more contextual error in this case.", Scope = "member", Target = "~M:WRA.Umbraco.Composers.MemberSavedServiceBusPublisher.Handle(Umbraco.Cms.Core.Notifications.MemberSavedNotification)")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1312:Variable names should begin with lower-case letter", Justification = "Variable Name cannot be lower case throw away variable", Scope = "member", Target = "~M:WRA.Umbraco.Composers.Jobs.ManipulateContent(Hangfire.Server.PerformContext)")]
[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "Using Swagger API Exceptions for NotFound", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.HousingStatisticsController.GetHousingStatisticListAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{WRA.UmbracoBridgeServices.HousingStatisticDto}}}")]
[assembly: SuppressMessage("Minor Code Smell", "S6667:Logging in a catch clause should pass the caught exception as a parameter.", Justification = "Using Swagger API Exceptions for NotFound", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.LegalHotlineController.GetHousingStatisticListAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{WRA.UmbracoBridgeServices.HousingStatisticDto}}}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "No period after swagger remarks for better developer experience", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.MemberSearchController.SearchMembersAsync(WRA.UmbracoBridgeServices.SearchMembersRequest)~System.Threading.Tasks.Task{PaginationResponse{WRA.UmbracoBridgeServices.MemberDto}}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "No period after swagger remarks for better developer experience", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.MemberEthicsTrainingController.GetCompanyMemberEthicsTrainingStatusesListAsync(System.Guid)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{WRA.UmbracoBridgeServices.CompanyMemberEthicsTrainingStatusDto}}}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "No period after swagger remarks for better developer experience", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.FundraisingReportController.GetFundraisingReportListAsync(System.Guid)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{WRA.UmbracoBridgeServices.FundraisingReportDto}}}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "No period after swagger remarks for better developer experience", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.MemberSearchApiController.SearchMembersAsync(WRA.UmbracoBridgeServices.SearchMembersRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{WRA.UmbracoBridgeServices.PaginationResponseOfMemberDto}}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "No period after swagger remarks for better developer experience", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.AgentEventRegistrationApiController.GetAgentEventRegistrationListByEventAsync(WRA.UmbracoBridgeServices.GetAgentEventRegistrationsByEventRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{WRA.UmbracoBridgeServices.AgentEventRegistrationDto}}}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "No period after swagger remarks for better developer experience", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.AgentEventRegistrationApiController.GetAgentEventRegistrationsEventListAsync(WRA.UmbracoBridgeServices.GetAgentEventRegistrationsEventListRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{WRA.UmbracoBridgeServices.AgentMeetingEventDetailDto}}}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "No period after swagger remarks for better developer experience", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.AgentEventRegistrationApiController.GetAgentEventRegistrationsIndividualListAsync(WRA.UmbracoBridgeServices.GetAgentEventRegistrationsIndividualListRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{WRA.UmbracoBridgeServices.AgentEventRegistrationDto}}}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "No period after swagger remarks for better developer experience", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.AgentEventRegistrationApiController.GetAgentEventRegistrationsListByIndividualAsync(WRA.UmbracoBridgeServices.GetAgentEventRegistrationsByIndividualRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{WRA.UmbracoBridgeServices.AgentEventRegistrationDto}}}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "No period after swagger remarks for better developer experience", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.FundraisingReportApiController.GetFundraisingReportAsync(WRA.UmbracoBridgeServices.GetFundraisingReportRequest)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "No period after swagger remarks for better developer experience", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.FundraisingReportApiController.GetFundraisingReportListAsync(System.Guid)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{WRA.UmbracoBridgeServices.FundraisingReportDto}}}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1629:Documentation text should end with a period", Justification = "No period after swagger remarks for better developer experience", Scope = "member", Target = "~M:WRA.Umbraco.Web.Controllers.Api.MemberEthicsTrainingApiController.GetCompanyMemberEthicsTrainingStatusesListAsync(System.Guid)~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.ActionResult{System.Collections.Generic.List{WRA.UmbracoBridgeServices.CompanyMemberEthicsTrainingStatusDto}}}")]
[assembly: SuppressMessage("Major Code Smell", "S2139:Exceptions should be either logged or rethrown but not both", Justification = "Incorrectly triggering", Scope = "module")]
[assembly: SuppressMessage("Major Code Smell", "S125:Sections of code should not be commented out", Justification = "format preference / duplicating", Scope = "module")]

// #todoeric check controller methods to make sure this is as intended S6964 https://rules.sonarsource.com/csharp/RSPEC-6964.
[assembly: SuppressMessage("SonarAnalyzer.CSharp", "S6964", Justification = "Generated swagger client", Scope = "namespaceanddescendants", Target = "~N:WRA.UmbracoBridgeServices")]
[assembly: SuppressMessage("Design", "CA1040:Avoid empty interfaces", Justification = "Tagging interface empty body is expected.", Scope = "type", Target = "~T:WRA.Umbraco.Configuration.IConfigurationSettings")]
[assembly: SuppressMessage("Major Code Smell", "S1144:Unused private types or members should be removed", Justification = "Placeholder possibly, otherwise delete", Scope = "member", Target = "~F:WRA.Umbraco.Web.Controllers.Api.CompanyEducationHistoryApiController._bridgeServiceClient")]
[assembly: SuppressMessage("Major Code Smell", "S1144:Unused private types or members should be removed", Justification = "Placeholder possibly, otherwise delete", Scope = "member", Target = "~F:WRA.Umbraco.Web.Controllers.Api.CompanyEducationHistoryApiController._logger")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1106:Code should not contain empty statements", Justification = "Marking Interface no need for a body", Scope = "type", Target = "~T:WRA.Umbraco.Configuration.IConfigurationSettings")]
